### ISSUE TITLE
conflict with linter 'whitespace.multi-func'

### ISSUE THREAD

**Issue by p3rs1st** [mvdan/gofumpt#321]
gofumpt has a rule `No empty lines around function bodies`, which is conflict with whitespace configuration `multi-func`.

The configuration enforces newlines (or comments) after every multi-line function signature, according to <https://golangci-lint.run/usage/linters/#whitespace>

`File is not properly formatted (gofumpt)`

```go
func A(
	a int,
) bool {

	return a == 0
}
```

`multi-line statement should be followed by a newline (whitespace)`

```go
func A(
	a int,
) bool {
	return a == 0
}
```

`.golangci.yml`

```yaml
linters:
  disable-all: true
  fast: false
  enable:
    - gofumpt
    - whitespace
linters-settings:
  whitespace:
    multi-func: true
```
